spring:
  r2dbc:
    username: root
    password: root
    url: r2dbc:postgresql://localhost:5432/postgres?schema=public

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

server:
  error:
    include-stacktrace: on_param